const tseslint = require('@typescript-eslint/eslint-plugin');
const angular = require('@angular-eslint/eslint-plugin');

module.exports = [
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/publish/**',
      '**/e2e/**',
      '**/playbook/**',
      '**/scripts/**',
      '**/server/**',
      '**/style-guide/**',
      '**/preview/**',
      '**/tools/**',
      '**/assistant/**',
      'karma.conf.js',
      'commitlint.config.js',
      'eslint.config.js'
    ],
  },

  ...tseslint.configs['flat/recommended'],

  {
    files: ['**/*.ts'],
    plugins: {
      '@angular-eslint': angular,
    },
    rules: {
      '@angular-eslint/component-class-suffix': ['error', { suffixes: ['Component', 'Directive'] }],
      '@angular-eslint/component-max-inline-declarations': 'error',
      '@angular-eslint/component-selector': ['error', { type: 'element', prefix: 'd', style: 'kebab-case' }],
      '@angular-eslint/computed-must-return': 'error',
      '@angular-eslint/consistent-component-styles': 'error',
      '@angular-eslint/contextual-decorator': 'error',
      '@angular-eslint/contextual-lifecycle': 'error',
      '@angular-eslint/directive-class-suffix': ['error', { suffixes: ['Component', 'Directive'] }],
      '@angular-eslint/directive-selector': 'off',
      '@angular-eslint/no-async-lifecycle-method': 'error',
      '@angular-eslint/no-attribute-decorator': 'error',
      '@angular-eslint/no-developer-preview': 'off',
      '@angular-eslint/no-duplicates-in-metadata-arrays': 'error',
      '@angular-eslint/no-empty-lifecycle-method': 'error',
      '@angular-eslint/no-experimental': 'off',
      '@angular-eslint/no-forward-ref': 'error',
      '@angular-eslint/no-implicit-take-until-destroyed': 'error',
      '@angular-eslint/no-input-prefix': 'error',
      '@angular-eslint/no-input-rename': 'off',
      '@angular-eslint/no-inputs-metadata-property': 'error',
      '@angular-eslint/no-lifecycle-call': 'error',
      '@angular-eslint/no-output-native': 'error',
      '@angular-eslint/no-output-on-prefix': 'off',
      '@angular-eslint/no-output-rename': 'error',
      '@angular-eslint/no-outputs-metadata-property': 'error',
      '@angular-eslint/no-pipe-impure': 'error',
      '@angular-eslint/no-queries-metadata-property': 'error',
      '@angular-eslint/no-uncalled-signals': 'off',
      '@angular-eslint/pipe-prefix': 'error',
      '@angular-eslint/prefer-host-metadata-property': 'error',
      '@angular-eslint/prefer-inject': 'error',
      '@angular-eslint/prefer-on-push-component-change-detection': 'error',
      '@angular-eslint/prefer-output-emitter-ref': 'error',
      '@angular-eslint/prefer-output-readonly': 'error',
      '@angular-eslint/prefer-signal-model': 'error',
      '@angular-eslint/prefer-signals': 'error',
      '@angular-eslint/prefer-standalone': 'error',
      '@angular-eslint/relative-url-prefix': 'error',
      '@angular-eslint/require-lifecycle-on-prototype': 'error',
      '@angular-eslint/require-localize-metadata': 'error',
      '@angular-eslint/runtime-localize': 'error',
      '@angular-eslint/sort-keys-in-type-decorator': 'error',
      '@angular-eslint/sort-lifecycle-methods': 'error',
      '@angular-eslint/use-component-selector': 'error',
      '@angular-eslint/use-component-view-encapsulation': 'off',
      '@angular-eslint/use-injectable-provided-in': 'error',
      '@angular-eslint/use-lifecycle-interface': 'error',
      '@angular-eslint/use-pipe-transform-interface': 'error',

      // ---- Custom overrides from .eslintrc.js ----
      'no-useless-constructor': 'off',
      'no-useless-concat': 'off',
      'no-unused-expressions': 'off',
      'max-params': 'off',
      '@typescript-eslint/no-useless-constructor': 'off',
      '@typescript-eslint/parameter-properties': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-var-requires': 'off',
      'complexity': ['error', { max: 40 }],
      'curly': 'error',
      'eol-last': 'error',
      'eqeqeq': ['error', 'smart'],
      'max-len': ['error', { code: 140 }],
      'no-console': ['error', {
        allow: [
          'log', 'warn', 'dir', 'timeLog', 'assert', 'clear', 'count',
          'countReset', 'group', 'groupEnd', 'table', 'dirxml', 'error',
          'groupCollapsed', 'Console', 'profile', 'profileEnd', 'timeStamp', 'context',
        ],
      }],
      'no-multiple-empty-lines': 'error',
      'no-shadow': 'off',
      'no-trailing-spaces': 'error',
      'no-unused-labels': 'error',
      'no-use-before-define': 'warn',
      'no-var': 'error',
      'prefer-const': 'error',
      'semi': 'error',
      'space-in-parens': ['error', 'never'],
      'spaced-comment': ['error', 'always'],
      '@typescript-eslint/dot-notation': 'off',
      'indent': ['error', 2, {
        FunctionDeclaration: { parameters: 'first' },
        FunctionExpression: { parameters: 'first' },
      }],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-misused-new': 'error',
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/prefer-function-type': 'error',
      '@typescript-eslint/unified-signatures': 'error',
      '@typescript-eslint/no-shadow': 'error',
      'prefer-promise-reject-errors': 'off',
      'max-nested-callbacks': ['error', 6],
      '@typescript-eslint/no-this-alias': 'off',
      'accessor-pairs': 'off',
      'max-depth': 'off',
      '@typescript-eslint/member-ordering': 'off',
      'array-callback-return': 'off',
    },
  },
];
